### ISSUE TITLE
Search is not returning a match

### ISSUE THREAD

**Issue by adriancoman** [luxw/fuse-kotlin#1]
Having a problem with the search, it's returning null thought I think it should return a match.

```
val fuse = Fuse()
val pattern = fuse.createPattern("galati") 
val result = fuse.search(pattern, "spatiu galati trei")
```

Expected the result.value to be a 0.0, but result is actually null.

What's strange is that the following works:
```
val fuse = Fuse()
val pattern = fuse.createPattern("gala") 
val result = fuse.search(pattern, "spatiu galati trei")
```

**Comment by matheusfinatti** [comment]
Thanks for pointing it out. Some logic was wrong due to a missing parenthesis. I have fixed and will release a new version
